/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute, setCatchHandler } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';

const PUBLIC_URL = process.env.PUBLIC_URL || '';
const OFFLINE_URL = PUBLIC_URL + '/offline.html';

clientsClaim();

// Precache all of the assets generated by the build (incl. index.html)
precacheAndRoute(self.__WB_MANIFEST);

// Install: cache offline fallback page so it's available when network fails
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open('offline-fallback-v1').then((cache) => cache.add(OFFLINE_URL))
  );
});

// Navigation: NetworkFirst → precache index.html → offline.html
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') return false;
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.match(fileExtensionRegexp)) return false;
    return true;
  },
  new NetworkFirst({
    cacheName: 'pages-v1',
    networkTimeoutSeconds: 5,
    plugins: [new ExpirationPlugin({ maxEntries: 32 })],
  }),
  'GET'
);

// Fallback when no route handles the request (e.g. strategy throws)
setCatchHandler(async ({ request }) => {
  if (request.mode === 'navigate') {
    const offlineResp = await caches.match(OFFLINE_URL);
    return offlineResp || new Response('Offline', { status: 503, statusText: 'Service Unavailable' });
  }
  return Response.error();
});

// Runtime cache: images (same-origin)
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  })
);

// Runtime cache: JS/CSS from same origin (e.g. lazy chunks) – CacheFirst for offline
registerRoute(
  ({ url }) =>
    url.origin === self.location.origin &&
    (url.pathname.endsWith('.js') || url.pathname.endsWith('.css')),
  new CacheFirst({
    cacheName: 'static-v1',
    plugins: [new ExpirationPlugin({ maxEntries: 60 })],
  })
);

// Skip waiting when requested (e.g. "Update available" prompt)
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
