#!/bin/bash
# 세금 계산 로직 수정 파일 배포 스크립트

echo "=== 세금 계산 로직 수정 파일 배포 ==="
echo ""
echo "변경된 파일:"
echo "1. server/utils/taxCalculator.js"
echo "2. server/utils/holidayPayCalculator.js"
echo ""
echo "서버 정보:"
echo "- 서버: ubuntu@54.180.88.34"
echo "- 프로젝트 경로: /var/www/convenience-store (확인 필요)"
echo ""
echo "배포 방법:"
echo "1. 올바른 SSH 키 경로를 찾아서 아래 명령어를 실행하세요:"
echo ""
echo "   scp -i <SSH_KEY_PATH> server/utils/taxCalculator.js ubuntu@54.180.88.34:/tmp/"
echo "   scp -i <SSH_KEY_PATH> server/utils/holidayPayCalculator.js ubuntu@54.180.88.34:/tmp/"
echo ""
echo "2. 서버에 SSH 접속:"
echo "   ssh -i <SSH_KEY_PATH> ubuntu@54.180.88.34"
echo ""
echo "3. 서버에서 파일 복사 및 재시작:"
echo "   sudo cp /tmp/taxCalculator.js /var/www/convenience-store/server/utils/"
echo "   sudo cp /tmp/holidayPayCalculator.js /var/www/convenience-store/server/utils/"
echo "   sudo pm2 restart convenience-store"
echo ""
echo "또는 직접 편집:"
echo "   sudo nano /var/www/convenience-store/server/utils/taxCalculator.js"
echo "   sudo nano /var/www/convenience-store/server/utils/holidayPayCalculator.js"

